### ISSUE TITLE
Plotting the tree

### ISSUE THREAD

**Issue by jesinj** [chrisspen/dtree#2]
Hi,

Is there a way to plot the tree after it has been built?

Jesin

**Comment by chrisspen** [comment]
There's no built-in way to plot it graphically, no, but it wouldn't be too hard to convert the nested dictionaries to a directed graph form usable by common plotting libraries.

If you look in the unittests, to debug, you can print it out using pprint. e.g.

    pprint(tree.to_dict(), indent=4)

**Comment by jesinj** [comment]
Hi,

So I already have a CART tree I have trained using wagon tools, its in txt format, something like this: 
((phone is _)
 ((next_accent is H*)
  ((syls_to_next_accent < 4.9)
   ((0.0518918 0.0666875))
   ((0.00570301 0.0156442)))
  ((sentence_numwords < 11.8)
   ((sentence_punc is ?)
    ((prev_prev_cplace is 0)
     ((0.0291537 0.0289554))
     ((0.0658966 0.127562)))
    ((next_phone is p)
     ((syls_to_next_accent < 2.7)
      ((0.16629 0.13985))
      ((0.0252639 0.0339438)))
     ((sentence_punc is !)
      ((0.0735759 0.0959023))


Is there a way to plot this?

**Comment by chrisspen** [comment]
Probably, but this is beyond the scope of this package. Sorry.
